spring:
  datasource:
    url: jdbc:mysql://localhost:3306/user_reservation_db?generateSimpleParameterMetadata=true
    username: root
    password: sabdullateef87
  flyway:
    enabled: true
    baselineOnMigrate: true

#    url: jdbc:postgresql://localhost:5432/users_blog_db